name: Build Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Asciidoctor
        run: |
         sudo apt-get install asciidoctor

      - name: Get README content
        run: |
          README_CONTENT=$(cat README.md)
          echo "${README_CONTENT}" >> documentation.adoc

      - name: Build Documentation
        run: |
          asciidoctor documentation.adoc -o output.html

